- name: Run Postman Collection
        run: |
          mkdir -p results
          # Este comando busca el archivo .json en TODO el proyecto autom√°ticamente
          FILE_PATH=$(find . -name "*.postman_collection.json" | head -n 1)
          echo "Found file at: $FILE_PATH"
          
          newman run "$FILE_PATH" \
          -r cli,htmlextra \
          --reporter-htmlextra-export results/report.html
