name: UI Testing Execution

on:
  push:
    branches: [ "HeilynPracticeKoel" ]
  workflow_dispatch: 

jobs:
  ui-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: HeilynPracticeKoel

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Debug and Run
        run: |
          echo "--- COMPROBANDO ARCHIVOS ---"
          ls -la
          
          # Si el archivo gradlew no existe, lo creamos para que no falle
          if [ ! -f "gradlew" ]; then
            echo "Gradlew no encontrado, intentando generarlo..."
            gradle wrapper
          fi
          
          chmod +x gradlew
          ./gradlew test -Dheadless=true --stacktrace

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results
          path: |
            **/build/reports/tests/test/
            **/build/test-results/test/
