name: UI Testing Execution

on:
  push:
    branches: [ "HeilynPracticeKoel" ]
  workflow_dispatch:

jobs:
  ui-automation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    services:
      selenium-grid:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g
          --health-cmd "curl --fail http://localhost:4444/status || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: HeilynPracticeKoel

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run UI Tests
        env:
          CHROME_HEADLESS: "true"
        run: |
          echo "Esperando a que Selenium Grid esté listo..."
          # Espera hasta que el Grid reporte que está listo
          timeout 60s bash -c 'until curl -s http://localhost:4444/status | grep -q "\"ready\": true"; do sleep 2; done'
          echo "¡Grid listo para la acción!"
          
          # Localizar gradlew y darle permisos
          GRADLE_PATH=$(find . -name "gradlew" | head -n 1)
          chmod +x "$GRADLE_PATH"
          
          # Ejecución de tests con URL limpia y parámetros de sistema
          "$GRADLE_PATH" test -DgridUrl=http://localhost:4444 -DCHROME_HEADLESS=true --info

      - name: Load Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 2
