name: UI Testing Execution

on:
  push:
    branches: [ "HeilynPracticeKoel" ]
  workflow_dispatch: 

jobs:
  ui-automation:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    services:
      # Contenedor de Chrome Standalone que actúa como nuestro Grid
      selenium-grid:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: HeilynPracticeKoel

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Sincronizado con tu JDK 21 local para evitar errores de red
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Tests
        env:
          CHROME_HEADLESS: "true"
        run: |
          # 1. ESPERA ACTIVA: Asegurar que el Grid esté listo antes de lanzar Gradle
          echo "Esperando a que Selenium Grid esté listo en localhost:4444..."
          timeout 60s bash -c 'until curl -s http://localhost:4444/status | grep -q "\"ready\": true"; do sleep 1; done'
          echo "¡Grid está encendido y listo!"

          # 2. LOCALIZAR GRADLEW Y EJECUTAR
          # Usamos localhost:4444 porque GitHub mapea los puertos de los services al host
          GRADLE_PATH=$(find . -name "gradlew" | head -n 1)
          
          if [ -z "$GRADLE_PATH" ]; then
            echo "Usando gradle global..."
            gradle test -DgridUrl=http://localhost:4444 -DCHROME_HEADLESS=true --stacktrace
          else
            GRADLE_DIR=$(dirname "$GRADLE_PATH")
            cd "$GRADLE_DIR"
            chmod +x gradlew
            ./gradlew test -DgridUrl=http://localhost:4444 -DCHROME_HEADLESS=true --stacktrace
          fi

      - name: Load Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@
