name: UI Testing Execution

on:
  push:
    branches: [ "HeilynPracticeKoel" ]
  workflow_dispatch: 

jobs:
  ui-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: HeilynPracticeKoel

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Cambia a '11' o '21' si es la que usas en IntelliJ
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run Gradle Tests
        run: |
          # 1. Encontrar el ejecutable
          GRADLE_PATH=$(find . -name "gradlew" -print -quit)
          GRADLE_DIR=$(dirname "$GRADLE_PATH")
          cd "$GRADLE_DIR"
          
          # 2. Dar permisos
          chmod +x gradlew
          
          # 3. Ejecutar y mostrar errores en consola
          ./gradlew test -Dheadless=true --info --stacktrace

      - name: Upload Test Reports
        if: always() # Esto garantiza que el reporte se suba SIEMPRE
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-report
          path: |
            **/build/reports/tests/test/**
            **/build/test-results/test/*.xml
