name: UI Testing Execution (CI/CD Pipeline)

on:
  push:
    branches: [ "HeilynPracticeKoel" ]
  workflow_dispatch: 

jobs:
  ui-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: HeilynPracticeKoel

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Debug and Run
        run: |
          echo "--- BUSCANDO PROYECTO ---"
          GRADLE_PATH=$(find . -name "gradlew" -print -quit)
          
          if [ -z "$GRADLE_PATH" ]; then
            echo "ERROR: No se encontr√≥ el archivo gradlew. Verifica tus carpetas."
            ls -R
            exit 1
          fi
          
          GRADLE_DIR=$(dirname "$GRADLE_PATH")
          echo "Proyecto encontrado en: $GRADLE_DIR"
          
          cd "$GRADLE_DIR"
          chmod +x gradlew
          
          # Ejecutamos con --stacktrace para ver el error real si falla
          ./gradlew test -Dheadless=true --stacktrace

      - name: Upload Test Reports
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results
          path: |
            **/build/reports/tests/test/
            **/build/test-results/test/
