name: UI Testing Execution

on:
  push:
    branches: [ "HeilynPracticeKoel", "main" ]
  workflow_dispatch: 

jobs:
  ui-automation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: HeilynPracticeKoel # Forzamos a que use tu rama con código

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Run Selenium Tests
      run: |
        # En Gradle no usamos 'mvn test', usamos './gradlew test'
        # Damos permisos de ejecución al wrapper
        chmod +x gradlew
        ./gradlew test -Dheadless=true

    - name: Upload Test Reports
      if: always() 
      uses: actions/upload-artifact@v4
      with:
        name: ui-test-results
        # Gradle guarda los reportes en build/reports/
        path: "**/build/reports/tests/test/"
