name: UI Testing Execution

on:
  push:
    branches: [ "HeilynPracticeKoel", "main" ]
  workflow_dispatch: 

jobs:
  ui-automation:
    runs-on: ubuntu-latest

    # Levantamos el Grid dentro de GitHub para que el RemoteWebDriver tenga a donde conectar
    services:
      selenium-grid:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: HeilynPracticeKoel

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Run Selenium Tests
      run: |
        # Usamos 'gradle' directamente porque no usas el wrapper (gradlew)
        # -DCHROME_HEADLESS=true activa tu l√≥gica de ChromeOptions
        # -DgridUrl apunta al servicio de Selenium Grid que levantamos arriba
        gradle test -DCHROME_HEADLESS=true -DgridUrl=http://localhost:4444/wd/hub

    - name: Upload Test Reports
      if: always() 
      uses: actions/upload-artifact@v4
      with:
        name: ui-test-results
        path: "**/build/reports/tests/test/"
